@startuml

hide circle
skinparam linetype ortho

entity Vote {
  *id: uuid <<generated>>
  --
  *restaurant_id: uuid <<FK>>
  *poll_id: uuid <<FK>>
}

entity User {
  *id: uuid <<generated>>
  --
  *username: text <<unique>>
  *password_hash: text
}

entity RestaurantSnapshot {
  *id: uuid <<generated>>
  --
'  *restaurant_id: uuid <<FK>>
'  *snapshot_id: uuid <<FK>>
  *datetime: timestamptz
}

entity Restaurant {
  *id: uuid <<generated>>
  --
  *name: text
  *restaurant_snapshot_id: uuid <<FK>>
  *voted_on: bool
}

entity MenuItem {
  *id: uuid <<generated>>
  --
  *restaurant_id: uuid <<FK>>
  *name: text
  price: money
}

Restaurant }o-up-|| RestaurantSnapshot
'Restaurant ||-left-o{ RestaurantSnapshot
MenuItem }o-up-|| Restaurant

RestaurantSnapshot ||-right-----o{ User : < creates
User ||-o{ Vote : > casts
Restaurant ||-o{ Vote

@enduml